# Generated by Django 4.2.18 on 2025-02-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approver',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requestdocument',
            name='status',
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='approval.requestdocument')),
            ],
        ),
        migrations.CreateModel(
            name='HighlightPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='approval.requestdocument')),
            ],
        ),
    ]
