# Generated by Django 4.2.18 on 2025-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approval_requestform_remove_highlightpoint_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='doc_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
