# Generated by Django 4.2.18 on 2025-02-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_alter_requestform_doc_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestform',
            options={},
        ),
        migrations.AddField(
            model_name='requirement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='HighlightPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='approval.requestform')),
            ],
        ),
    ]
