# Generated by Django 4.2.18 on 2025-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_alter_requestform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='doc_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
