# Generated by Django 4.2.18 on 2025-02-06 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_alter_requestform_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
