# Generated by Django 4.2.18 on 2025-02-06 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_requirement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
