# Generated by Django 4.2.18 on 2025-02-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0011_alter_requestform_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
