# Generated by Django 4.2.18 on 2025-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0012_approval_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_documents/'),
        ),
    ]
