# Generated by Django 4.2.18 on 2025-02-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
