# Generated by Django 4.2.18 on 2025-02-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0016_requestform_has_query_requestform_query_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='has_query',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
