# Generated by Django 4.2.18 on 2025-02-28 09:23

import approval.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0018_alter_requestform_has_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_documents/', validators=[approval.models.validate_file_size]),
        ),
    ]
