# Generated by Django 4.2.18 on 2025-03-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0020_requirementrevision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementRevision',
        ),
    ]
