# Generated by Django 4.2.18 on 2025-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0021_delete_requirementrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_approver_body', models.TextField(default='Default first approver email content.')),
                ('next_approver_body', models.TextField(default='Default next approver email content.')),
            ],
        ),
    ]
