# Generated by Django 4.2.18 on 2025-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0022_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='query_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
