# Generated by Django 4.2.18 on 2025-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0023_approval_query_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='has_query',
            field=models.IntegerField(default=0),
        ),
    ]
