# Generated by Django 4.2.18 on 2025-03-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_voucher_number', models.CharField(max_length=50)),
                ('expense_head', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_gst_number', models.CharField(max_length=15)),
                ('cost_center_department', models.CharField(max_length=100)),
                ('department_expense_code', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('terminal_name', models.CharField(max_length=100)),
                ('profit_center_segment', models.CharField(max_length=100)),
                ('tds_application', models.BooleanField()),
                ('tds_section', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=50)),
                ('itc_gst_r2b', models.CharField(max_length=50)),
                ('itc_claimed', models.BooleanField()),
                ('vendor_type', models.CharField(max_length=100)),
                ('itc_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_forms', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
