# Generated by Django 4.2.18 on 2025-03-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0002_remove_formsubmission_cost_center_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('doc_number', models.CharField(max_length=50, unique=True)),
                ('profit_center', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
