# Generated by Django 4.2.18 on 2025-03-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpms', '0003_bookingform'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
