# Generated by Django 4.2.18 on 2025-03-18 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0004_bookingform_created_by_bookingform_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
