# Generated by Django 4.2.18 on 2025-03-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0006_bookingform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='updated_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
