# Generated by Django 4.2.18 on 2025-03-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0008_updatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='documents',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kpms.bookingform')),
            ],
        ),
    ]
