# Generated by Django 4.2.18 on 2025-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0009_remove_bookingform_documents_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
