# Generated by Django 4.2.18 on 2025-03-20 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpms', '0011_rename_form_document_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='user',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
