# Generated by Django 4.2.18 on 2025-03-25 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpms', '0013_querylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylog',
            old_name='resolve_comment',
            new_name='resolution_comment',
        ),
        migrations.RenameField(
            model_name='querylog',
            old_name='created_at',
            new_name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='update_details',
        ),
        migrations.AddField(
            model_name='querylog',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raised_queries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querylog',
            name='updated_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
