# Generated by Django 4.2.18 on 2025-03-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpms', '0014_rename_resolve_comment_querylog_resolution_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='cgst_value',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='igst_value',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='profit_center',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='sgst_value',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='taxable_value',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientAssigneeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignees', models.ManyToManyField(related_name='mapped_clients', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_mapping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingform',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpms.documenttype'),
        ),
    ]
