# Generated by Django 4.2.18 on 2025-03-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0015_documenttype_remove_bookingform_cgst_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassigneemapping',
            name='validation_process',
            field=models.CharField(choices=[('Validation 1', 'Validation 1'), ('Validation 2', 'Validation 2'), ('Validation 3', 'Validation 3')], default='Validation 1', max_length=20),
        ),
    ]
