# Generated by Django 4.2.18 on 2025-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0016_clientassigneemapping_validation_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Raise Query', 'Raise Query'), ('Validation', 'Validation'), ('Closed', 'Closed')], default='In Progress', max_length=20),
        ),
    ]
