# Generated by Django 4.2.18 on 2025-03-30 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpms', '0017_alter_bookingform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
