# Generated by Django 4.2.18 on 2025-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0018_bookingform_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Raise Query', 'Raise Query'), ('Validation In Progress', 'Validation In Progress'), ('Client Validation', 'Client Validation'), ('Validation', 'Validation'), ('Closed', 'Closed')], default='In Progress', max_length=30),
        ),
    ]
