# Generated by Django 4.2.18 on 2025-04-02 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpms', '0020_querydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='querydocument',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kpms.querylog'),
            preserve_default=False,
        ),
    ]
